### ISSUE TITLE
Create a POAP for testing the flow

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/L2E#21]
POAP generation, distribution, testing is needed.

- [ ] Create a POAP for testing purposes
- [ ] Check the delivery of claim link to user successfully completed the quiz
- [ ] Check the low reserve notification
- [ ] Check the top up of number of POAPs, if it is low below an acceptable reserve

**Comment by pnpancholi** [comment]
Hey, I have been looking into the codebase for courses. Do we have any courses already? Or can I make any POAP for testing?

**Comment by poojaranjan** [comment]
This issue isn't relevant any more.
